server:
  # 端口号
  port: 80


spring:
  # 连接数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///app?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    username: 13478530122@163.com
    password: yangpeng1211
    activeUrl: http://10.9.63.232

mybatis:
  configuration:
    # 驼峰映射
    map-underscore-to-camel-case: true
  # 扫描映射文件.
  mapper-locations: classpath:mapper/*.xml
  # 别名
  type-aliases-package: com.qf.entity
  # typeHandler
  type-handlers-package: com.qf.typehandler

# 分页助手
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# shiro的路径
shiro:
  loginUrl: /
  unauthorizedUrl: /
